/*
auto-generated by: https://github.com/pmndrs/gltfjsx
author: Willy Decarpentrie (https://sketchfab.com/skudgee)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/mech-drone-8d06874aac5246c59edb4adbe3606e0e
title: Mech Drone
*/
import React, { useRef, useState, useEffect } from "react";
import { useFrame } from "react-three-fiber";
import { useGLTF } from "@react-three/drei/useGLTF";
import * as THREE from "three";
import { useThree } from "react-three-fiber";
import { useDrag } from "react-use-gesture";

// https://sketchfab.com/3d-models/mech-drone-8d06874aac5246c59edb4adbe3606e0e
export default function RobotModel(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/robot/scene.gltf");

  const actions = useRef();
  const [mixer] = useState(() => new THREE.AnimationMixer());

  const [position, setPosition] = React.useState([0, -10, -2]);
  const { size, viewport } = useThree();
  const aspect = size.width / viewport.width;

  const bind = useDrag(
    ({ offset: [x, y] }) => {
      const [, , z] = position;
      setPosition([x / aspect, -y / aspect, z]);
    },
    { pointerEvents: true }
  );

  useFrame((state, delta) => mixer.update(delta));
  useEffect(() => {
    actions.current = {
      Take_001: mixer.clipAction(animations[0], group.current),
    };
    actions.current.Take_001.play();
    return () => animations.forEach((clip) => mixer.uncacheClip(clip));
  }, []);
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      {...bind()}
      position={position}
      scale={[0.03, 0.03, 0.03]}
      rotation={[0, 55, 0]}
    >
      <group
        rotation={[-Math.PI / 2, 0, 0]}
        userData={{ name: "RootNode (gltf orientation matrix)" }}
      >
        <group userData={{ name: "RootNode (model correction matrix)" }}>
          <group
            rotation={[Math.PI / 2, 0, 0]}
            userData={{ name: "Drone.FBX" }}
          >
            <group userData={{ name: "RootNode" }}>
              <primitive object={nodes._rootJoint} />
              <skinnedMesh
                material={materials.Robot}
                geometry={nodes.droid_Robot_0.geometry}
                skeleton={nodes.droid_Robot_0.skeleton}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/robot/scene.gltf");
